#!/usr/bin/python3
# -*- coding: utf-8 -*-
from os import listdir, rename
from os.path import isfile, isdir, join, splitext
import re
import json
import time
import base64

build_at = time.time()

origin_file = open("ttscache.json")
origindata = json.loads(origin_file.read())
origin_file.close()

input_file = open("ttscache_new.json")
ttsdata = json.loads(input_file.read())
input_file.close()

for key in ttsdata:
  if key not in origindata["ttscache"]:
    base64_bytes = ttsdata[key].encode('ascii')
    message_bytes = base64.b64decode(base64_bytes)
    f = open("ttscache/" + key + ".ogg", 'wb')
    f.write(message_bytes)
    f.close()
    origindata["ttscache"].append(key)

origindata["ttscache"].sort()
origindata["build"] = build_at

origin_file = open("ttscache.json", "w")
origin_file.write(json.dumps(origindata, ensure_ascii=False, indent=2))
origin_file.close()

version_file = open("version.json")
version = json.loads(version_file.read())
version_file.close()
version["ttscache"] = build_at
version_file = open("version.json", "w")
version_file.write(json.dumps(version, ensure_ascii=False, indent=2))
version_file.close()
