#!/usr/bin/python3
# -*- coding: utf-8 -*-
from os import listdir
from os.path import isfile, isdir, join, splitext
import re
import json
import time;

files = listdir("audio");

output = {
  "index": {},
  "audio": [],
  "library": {},
  "build": time.time()
}

for f in files:
  filename, extension = splitext(f)
  if extension != ".mp3":
    continue
  if filename[-1].isdigit():
    number = re.findall(r'\d+', filename)[-1]
    filename = filename[0:len(filename) - len(number)]

  first_char = filename[0]

  if first_char not in output["index"]:
    output["index"][first_char] = [filename]
  elif filename not in output["index"][first_char]:
    output["index"][first_char].append(filename)

  if filename not in output["audio"]:
    output["audio"].append(filename)
    print(filename)

  if filename not in output["library"]:
    output["library"][filename] = [f]
  else:
    output["library"][filename].append(f)
  
  

print("指令數量：" + str(len(output["audio"])))

fp = open("audio.json", "w")
fp.write(json.dumps(output, ensure_ascii=False, indent=2))
fp.close()
